INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Abricot');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Agneau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Agrume');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Aiguillettes de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ail');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ail séché');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Alcool');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Algue');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Algue marine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Amande');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Amande en poudre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Amandes hachées');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Amidon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Amidon de maïs');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ananas');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Anchois');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Aneth');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Armagnac');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Artichaut');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Asperge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Aubergine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Aubergine grillée');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Aubergine préfrite');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Avocat');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Avoine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Avoine complète');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bacon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Banane');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Basilic');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Basilic séché');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Betterave');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Beurre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Beurre demi-sel');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Beurre doux');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Beurre frais');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Beurre salé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bière');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Biscuit');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Blanc de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Blanc d''œuf');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Blé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Blé complet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bœuf');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon de bœuf');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon de cuisson');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon de volaille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Bouillon végétal');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Boulghour');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Brocoli');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cabillaud');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cacahuètes grillées');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cacao');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Café');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Café moulu');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Calamar');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Canard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cannelle');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Caramel au beurre salé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cardamome');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Carnitine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Carotte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Carottes râpées');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Céleri');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Céleri-rave');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cerise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cerise noire');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Champignon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Champignons de Paris');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chapelure');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Châtaigne');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Châtaigne d''eau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('cheddar');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chocolat au lait');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chocolat blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chocolat en poudre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chocolat noir');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chocolat supérieur au lait');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cholécalciférol');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('chorizo');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chou');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chou blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chou rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chou vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Choucroute');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Chou-fleur');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ciboulette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Citron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Citron confit');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Citron vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Citronnelle');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Clémentine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cœurs d''artichauts');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cognac');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Coing');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Colin d''Alaska');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Collagène');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Colorant');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Colza');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Compote de pommes');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Comte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Concombre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Coque');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Coriandre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cornichon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Coulis de tomates');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Courge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Courge butternut');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Courgette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Courgette grillée');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Couscous');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crabe');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème aigre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème de noix de coco');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème fraîche');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème fraîche épaisse');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème fraîche liquide');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème légère');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème liquide');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crème pâtissière');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crepe');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crevette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crevette à pattes blanches');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crevettes décortiquées');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crispies de céréales');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Croûte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Croûte non comestible');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Croûton');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Crustacés');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cuisse de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cuivre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Cumin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Curcuma');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Curry');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Dinde');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Eau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Eau de coco');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Eau de cuisson');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Eau de source');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Eau gazeuse');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Échalote');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Emmental');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Emmental râpé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Épinard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine complète');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine d''avoine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine d''avoine complète');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de blé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de blé complète');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de blé t80');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de blé type 65');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de céréales');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de maïs');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Farine de sarrasin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filet de colin d''Alaska');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filet de dinde');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filet de porc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filet de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filets de maquereaux');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Filets de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('filets-de-sardines');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Flageolets');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Flageolets verts');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fleur de sel');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fleur de sel de Guérande');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Flocons d''avoine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Flocons de blé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie de canard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie de porc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie de volaille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie gras de canard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie gras de canard du sud-ouest');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Foie maigre de canard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fond de porc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fond de veau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fraise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Framboise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage cheddar');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage de chèvre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage frais');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fromage mozzarella');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fruit de la passion');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fruits confits');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fruits de mer');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fruits rouges');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Fruits séchés');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Galette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Galette de riz');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Gaufrette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Gingembre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('gorgonzola');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('gouda');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Gousse de vanille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Haricot');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Haricot vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Haricots blancs');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Herbes de provence');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Homard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile de coco');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile de colza');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile de soja');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile de tournesol');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile d''olive');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Huile végétale');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jambon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jambon cru');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jambon cuit');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jaune d''œuf');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus concentré de carotte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus concentré de citron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus concentré de fruits');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus concentré pulpé de citron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''ananas');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''ananas à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''ananas concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de betterave');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de betterave concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de betterave rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de betterave rouge concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de carotte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de carotte noire');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de carotte noire concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de cassis à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de céleri');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de céleri concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de cerise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de citron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de citron en poudre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de citron vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de citron vert à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de citron vert concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de clémentine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de fraise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de framboise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de framboise à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de fruit de la passion');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de fruit de la passion à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de fruits');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de grenade');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de légumes');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de pamplemousse');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de pamplemousse rose');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de poire');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de pomme');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de pomme à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de potiron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de raisin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de raisin blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de raisin concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de soja');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de sureau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de sureau concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de tomate');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus de tomate à partir de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''oignon concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''orange');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''orange à base de concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Jus d''orange concentré');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ketchup');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lait');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lait de chèvre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lait de noix de coco');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lait de soja');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Langouste rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Langoustine commune');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lard fumé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lardon fumé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lardons');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lentille verte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lentilles');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Lentilles corail');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Levure');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Levure chimique');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Levure de bière');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Levure de boulanger');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Litchi');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Maïs');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Mandarine');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Mangue');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Maquereau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Mascarpone');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Mayonnaise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Melon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Menthe');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Merguez');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Merlu');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Miel');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Moule');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Moutarde');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('mozzarella');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Muscadet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Myrtille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Navet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noisette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noisettes entières');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noix');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noix de cajou');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noix de coco');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noix de pécan');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Noix de saint-jacques');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Œuf dur');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Oignon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Olive verte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Olives');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Olives noires');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Orange');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pain');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pain de mie');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pain de mie complet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pamplemousse');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pamplemousse rose');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Paprika');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Parmesan');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pastèque');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Patate douce');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pâte');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pâte feuilletée');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pêche');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Persil');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Petits pois');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Piment');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pistache');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poire');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poireau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pois chiche');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poisson');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poitrine de porc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poivre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poivron');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poivron jaune');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poivron rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poivron vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pomme');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pomme de terre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Porto');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poudre d''ail');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poudre de curcuma');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Prune');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Pruneau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Quinoa blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Quinoa rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Radis');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Raisin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Raisin blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Raisin sec');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ravioli');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('reblochon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Réglisse');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Rhubarbe');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Rhum');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Ricotta');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('riesling');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Riz');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Riz basmati');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Riz blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Riz complet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Riz rond');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Salade');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sauce au soja');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sauce béchamel');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sauce tomate');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Saucisse de porc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Saumon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Saumon fumé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sel fin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Semoule');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Soja');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sucre de canne');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sucre glace');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Sucre liquide');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Surimi');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Thé');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Thé noir');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Thé vert');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Thon');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Thym');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Tomate');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Tomate cerise');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Truffe');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Truite');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vanille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vanille en poudre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Veau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vermicelle');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande bovine hachée');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de bœuf');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de canard');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de dinde');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de lapin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de mouton');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de poulet');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de veau');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Viande de volaille');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vin blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vin de liqueur');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vin rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre balsamique');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre d''alcool');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre de vin');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre de vin blanc');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigre de vin rouge');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Vinaigrette');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Whisky');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Yaourt');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Zeste d''orange');
INSERT INTO [dbo].[Ingredient]([Name]) VALUES ('Zestes de citron');
