INSERT INTO [dbo].[Measure]([Name]) VALUES ('Tasse');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('Cuillère à café');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('g');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('Kg');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('L');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('mL');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('Pincée');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('cl');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('Tranche');
INSERT INTO [dbo].[Measure]([Name]) VALUES ('Cuillère à soupe');
